# This will be the typical structure of 
# the input file for the input file for the profile code. 

# Upper limit of velocity pulsation. Units are in km/s.
# This velocity is used to compute what wave_lenght block will be read
# from the intensity grids.
max_velocity = 1.0e2

# Path to the directory where the intensity grid files are stored
path_to_grids = "./grids/nadyalike_grids/"

# Set the wave length range. The units are in nm 
[wavelength_range]
start = 4110.0
end = 4140.0
step = 0.01

# Collection of the intensity grid files
# Each intensity grid contains the following information
# Associated temperature in Kelvin
# Associated value for the logarithm of it's surface gravity
# File name of the intensity grid. 
[[intensity_grids]]
Nadya = {temperature = 21000.0, log_gravity = 3.5, metalicity=0.02, filename = "lp00000_21000_03500_0200..imu"}
[[intensity_grids]]
Nadya = {temperature = 21000.0, log_gravity = 4.5, metalicity=0.02, filename = "lp00000_21000_04500_0200..imu"}
[[intensity_grids]]
Nadya = {temperature = 24000.0, log_gravity = 3.5, metalicity=0.02, filename = "lp00000_24000_03500_0200..imu"}
[[intensity_grids]]
Nadya = {temperature = 24000.0, log_gravity = 4.5, metalicity=0.02, filename = "lp00000_24000_04500_0200..imu"}
